version: '3.7'


x-pg: &db-base
    image: postgres:11
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_NAME=postgres


services:
  db:
    <<: *db-base
